# Site settings
title: 杨比轩
baseurl: "/blog" # begin with /repo-name if use as project, else leave empty for gh-pages
url: "http://xiaopihai7256.hithub.io" # default is empty

# Build settings
kramdown:
  input: GFM
permalink: pretty

# Third-party services
# just leave empty to disable it
google_analytics:
disqus_shortname:
