# Site settings
title: 爬坑历程
baseurl: "" # begin with /repo-name if use as project, else leave empty for gh-pages
url: "https://xiaopihai7256.github.io" # default is empty

# Build settings
input: GFM
permalink: pretty
kramdown: 
  auto_ids: true  
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo


# Third-party services
# just leave empty to disable it
google_analytics:
disqus_shortname:
