# Site settings
title: 杨比轩
baseurl: "" # begin with /repo-name if use as project, else leave empty for gh-pages
url: "https://xiaopihai7256.github.io" # default is empty

# Build settings
markdown: kramdown
  input: GFM
permalink: pretty

# Third-party services
# just leave empty to disable it
google_analytics:
disqus_shortname:
